[package]
name = "omp-control-room"
version = "1.0.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-single-instance = "2"
tauri-plugin-window-state = "2"
tauri-plugin-dialog = "2"
tauri-plugin-clipboard-manager = "2"
tauri-plugin-opener = "2"
tauri-plugin-notification = "2"
serde_json = "1"
dunce = "1"
parking_lot = "0.12"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
